/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ["Inter var"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        //Custom
        gray: {
          1: "var(--colors-gray1)",
          2: "var(--colors-gray2)",
          3: "var(--colors-gray3)",
          4: "var(--colors-gray4)",
          5: "var(--colors-gray5)",
          6: "var(--colors-gray6)",
          7: "var(--colors-gray7)",
          8: "var(--colors-gray8)",
          9: "var(--colors-gray9)",
          10: "var(--colors-gray10)",
          11: "var(--colors-gray11)",
          12: "var(--colors-gray12)",
        },
        grayA: {
          0: "var(--colors-grayA0)",
          1: "var(--colors-grayA1)",
          2: "var(--colors-grayA2)",
          3: "var(--colors-grayA3)",
          4: "var(--colors-grayA4)",
          5: "var(--colors-grayA5)",
          6: "var(--colors-grayA6)",
          7: "var(--colors-grayA7)",
          8: "var(--colors-grayA8)",
          9: "var(--colors-grayA9)",
          10: "var(--colors-grayA10)",
          11: "var(--colors-grayA11)",
          12: "var(--colors-grayA12)",
        },
        neutral: {
          1: "var(--colors-neutral1)",
        },
        blue: {
          1: "var(--colors-blue1)",
          2: "var(--colors-blue2)",
          3: "var(--colors-blue3)",
          4: "var(--colors-blue4)",
          5: "var(--colors-blue5)",
          6: "var(--colors-blue6)",
          7: "var(--colors-blue7)",
          8: "var(--colors-blue8)",
          9: "var(--colors-blue9)",
          10: "var(--colors-blue10)",
          11: "var(--colors-blue11)",
          12: "var(--colors-blue12)",
        },
        blueA: {
          1: "var(--colors-blueA1)",
          2: "var(--colors-blueA2)",
          3: "var(--colors-blueA3)",
          4: "var(--colors-blueA4)",
          5: "var(--colors-blueA5)",
          6: "var(--colors-blueA6)",
          7: "var(--colors-blueA7)",
          8: "var(--colors-blueA8)",
          9: "var(--colors-blueA9)",
          10: "var(--colors-blueA10)",
          11: "var(--colors-blueA11)",
          12: "var(--colors-blueA12)",
        },
        green: {
          1: "var(--colors-green1)",
          2: "var(--colors-green2)",
          3: "var(--colors-green3)",
          4: "var(--colors-green4)",
          5: "var(--colors-green5)",
          6: "var(--colors-green6)",
          7: "var(--colors-green7)",
          8: "var(--colors-green8)",
          9: "var(--colors-green9)",
          10: "var(--colors-green10)",
          11: "var(--colors-green11)",
          12: "var(--colors-green12)",
        },
        amber: {
          1: "var(--colors-amber1)",
          2: "var(--colors-amber2)",
          3: "var(--colors-amber3)",
          4: "var(--colors-amber4)",
          5: "var(--colors-amber5)",
          6: "var(--colors-amber6)",
          7: "var(--colors-amber7)",
          8: "var(--colors-amber8)",
          9: "var(--colors-amber9)",
          10: "var(--colors-amber10)",
          11: "var(--colors-amber11)",
          12: "var(--colors-amber12)",
        },
        red: {
          1: "var(--colors-red1)",
          2: "var(--colors-red2)",
          3: "var(--colors-red3)",
          4: "var(--colors-red4)",
          5: "var(--colors-red5)",
          6: "var(--colors-red6)",
          7: "var(--colors-red7)",
          8: "var(--colors-red8)",
          9: "var(--colors-red9)",
          10: "var(--colors-red10)",
          11: "var(--colors-red11)",
          12: "var(--colors-red12)",
        },
        teal: {
          1: "var(--colors-teal1)",
          2: "var(--colors-teal2)",
          3: "var(--colors-teal3)",
          4: "var(--colors-teal4)",
          5: "var(--colors-teal5)",
          6: "var(--colors-teal6)",
          7: "var(--colors-teal7)",
          8: "var(--colors-teal8)",
          9: "var(--colors-teal9)",
          10: "var(--colors-teal10)",
          11: "var(--colors-teal11)",
          12: "var(--colors-teal12)",
        },
        bg: "var(--colors-bg)",
        lowContrast: "var(--colors-lowContrast)",
        highContrast: "var(--colors-highContrast)",
        focus: "var(--colors-focus)",
        grid: "var(--colors-grid)",
      },
      boxShadow: {
        small: "0 5px 10px rgba(0, 0, 0, 0.12)",
        medium: "0 8px 30px rgba(0, 0, 0, 0.12)",
        large: "0 30px 60px rgba(0, 0, 0, 0.12)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      backgroundImage: {
        "gradient-custom": "linear-gradient(45deg, var(--tw-gradient-stops))",
      },
      backgroundSize: {
        "size-200": "200% 100%",
      },
    },
  },
  plugins: [],
};